### ISSUE TITLE
Add support for persisted models

### ISSUE THREAD

**Issue by kaklakariada** [exasol/metabase-driver#53]
Metabase 0.44.0 added persisted models in https://github.com/metabase/metabase/pull/21109 with driver features `:persist-models` and `:persist-models-enabled`. We should add support for persisted models to the Exasol driver.

See
* [discussion in Metabase forum](https://discourse.metabase.com/t/support-persisted-models-in-our-driver/21656) for details.
* [Metabase documentation](https://www.metabase.com/docs/latest/data-modeling/models#model-caching)

**Comment by redcatbear** [comment]
Shelved because not in roadmap focus.
