### ISSUE TITLE
Should we move the JDBC driver to 7.1.20?

### ISSUE THREAD

**Issue by paoliniluis** [exasol/metabase-driver#71]
Reviewing our bundle I saw we use https://repo1.maven.org/maven2/com/exasol/exasol-jdbc/7.1.16/exasol-jdbc-7.1.16.jar, but 7.1.20 is available. Should we update it?

**Comment by kaklakariada** [comment]
Hi @paoliniluis!
Thanks for your ticket! We will upgrade the JDBC driver when we adapt the driver to the final version of Metabase 0.47 in https://github.com/exasol/metabase-driver/issues/70. Currently only a release candidate [0.47.0-RC2](https://github.com/metabase/metabase/releases/tag/v0.47.0-RC2) is available.
